config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :categories, except: %i[ show ]
  resources :products, path: "/"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }

  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images

  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 3 }
  validates :price, presence: true

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :category, only: %i[ edit update destroy ]

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, flash: { notice: t("common.created", model: Category.model_name.human) }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, flash: { notice: t("common.updated", model: Category.model_name.human) }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy!

    redirect_to categories_url, flash: { notice: t("common.destroyed", model: Category.model_name.human) }
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :product, only: %i[show edit update destroy]

  def index
    @categories = Category.order(name: :asc).load_async
    @products = Product.with_attached_images.order(created_at: :desc).load_async
    if params[:category_id]
      @products = @products.where(category_id: params[:category_id])
    end
    if params[:min_price].present?
      @products = @products.where("price >= ?", params[:min_price])
    end
    if params[:max_price].present?
      @products = @products.where("price <= ?", params[:max_price])
    end
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, flash: { notice: t("common.created", model: Product.model_name.human) }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to products_path, flash: { notice: t("common.updated", model: Product.model_name.human) }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy
    redirect_to products_path

    flash[:notice] = t("common.destroyed", model: Product.model_name.human)
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, images: [])
  end

  def product
    @product ||= Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <%= category.name %>
  </p>
  <%= link_to t('common.actions.edit'), edit_category_path(category)%>
  <%= link_to t('common.actions.delete'), category_path(category), data: { turbo_method: :delete, turbo_confirm: t('common_confirm') }%>
</div>

app/views/categories/_form.html.erb
<%= link_to Category.model_name.human(count: 2), categories_path %>
<div>
  <% @category.errors.full_messages.each do |error|%>
    <p><%= error %></p>
  <% end %>
</div>
<%= form_with(model: category) do |form| %>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, Category.model_name.human %>
<h1><%= t('.title') %></h1>
<%= render "form", category: @category %>
<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1> <%= Category.model_name.human(count: 2) %> </h1>
<%= render partial: 'category', collection: @categories %>
<%= link_to t('common.actions..new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>
<%= render "form", category: @category %>
<div>
  <%= link_to t('common.actions.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ecommerce" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/flash" %>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id) do%>
  <%= category.name %>
<% end %>

app/views/products/_form.html.erb
<%= link_to Product.model_name.human(count: 2), products_path %>
<div>
  <% @product.errors.full_messages.each do |error|%>
    <p><%= error %></p>
  <% end %>
</div>
<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :category_id %><br>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>
  <% @product.images.each do |image| %>
    <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
  <% end %>
  <%= form.file_field :images, multiple: true %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div>
  <%= product.name%>
  <%= product.description%>
  <%= product.price%>
  <% product.images.each do |image| %>
     <%= image_tag image, width: 200 %>
  <% end %>
  <%= link_to t('common.actions.go_to'), product_path(product), 'data-turbo-frame': '_top' %>
  <%= link_to t('common.actions.edit'), edit_product_path(product) %>
  <%= link_to t('common.actions.delete'), product_path(product), data: { turbo_method: :delete, turbo_confirm: 'Estás seguro?' } %>
</div>

app/views/products/edit.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'categories' do %>
  <h1><%= t('.title') %></h1>
  <div>
    <%= link_to Category.model_name.human(count: 2), categories_path %>
  </div>
  <div>
    <%= link_to t('common.actions.new'), new_product_path %>
  </div>
  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
    <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price] %>
  <% end %>
  <div>
    <%= link_to t('.all'), products_path %>
    <%= render partial: 'category', collection: @categories %>
    <%= render partial: 'product', collection: @products %>
  </div>
<% end %>

app/views/products/new.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form' %>

app/views/products/show.html.erb
<%= @product.name %>
<%= @product.description %>
<%= @product.price %>
<% @product.images.each do |image| %>
  <%= image_tag image, width: 200 %>
<% end %>
<%= link_to t('common.actions.edit'), edit_product_path(@product) %>
<%= link_to t('common.actions.delete'), product_path(@product), data: { turbo_method: :delete, turbo_confirm: t('common.confirm') } %>

app/views/shared/_flash.html.erb
<%= notice %>
<%= alert %>

app/views/shared/_header.html.erb
<h1>Ecommerce</h1>